name: CI/CD Pipeline for Streamlit RAG Project

on:
  push:
    branches: [ main ]  # Run the workflow on commits to main
  pull_request:
    branches: [ main ]

jobs:
  # CI Job: Testing and Building Docker Image
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust to your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest  # Replace with your test command

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/streamlit-rag:latest .

      - name: Push Docker image
        run: docker push your-dockerhub-username/streamlit-rag:latest

