name: CI/CD Pipeline for Streamlit RAG Project

on:
  push:
    branches: [ main ]  # Run the workflow on commits to main
  pull_request:
    branches: [ main ]

jobs:
  # CI Job: Testing and Building Docker Image
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust to your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest  # Replace with your test command

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/streamlit-rag:latest .

      - name: Push Docker image
        run: docker push your-dockerhub-username/streamlit-rag:latest

  # CD Job: Deploy to server (e.g., Azure, AWS)
  deploy:
    runs-on: ubuntu-latest
    needs: test_and_build  # Only deploy if tests and build succeed

    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/streamlit-rag:latest
            docker stop streamlit_rag || true
            docker rm streamlit_rag || true
            docker run -d -p 8501:8501 --name streamlit_rag your-dockerhub-username/streamlit-rag:latest
